In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier

In [2]:
#Apple or Orange
#The 2 features that we are looking at are weight and skin
weight = [140, 130, 150, 170]
skin = ['Smooth', 'Smooth', 'Bumpy', 'Bumpy']
#Takes the 2 arrays in, converts them to numpy arrays and returns a 2d numpy array
stack = np.column_stack((np.array(weight), np.array(skin)))
#To show that we did it right
print(stack)
#The labels we need
fruit = ['Apple', 'Apple', 'Orange', 'Orange']
print(fruit)

[['140' 'Smooth']
 ['130' 'Smooth']
 ['150' 'Bumpy']
 ['170' 'Bumpy']]
['Apple', 'Apple', 'Orange', 'Orange']


In [3]:
#Now that we know that our arrays are being displayed correctly, we'll change the strings to ints
#In most situations we'd write a loop to go through the arrays and replace the vals
#0 = Smooth, 1 = Bumpy
skin=[0,0,1,1]
#0=Apple 1=Orange
fruit = [0,0,1,1]
#Make them into a 2d array now for use
features = np.column_stack((np.array(weight), np.array(skin)))
print(features)


[[140   0]
 [130   0]
 [150   1]
 [170   1]]


In [4]:
#Creates a classifier
clf = DecisionTreeClassifier()

In [5]:
#Trains the classifier with our data
clf = clf.fit(features, fruit)


In [6]:
#Print the proper label
def labelPrediction(predicted):
    if predicted == 0:
        predicted = 'Apple'
    elif predicted == 1:
        predicted = 'Orange'
    print('Prediction: ', predicted)

In [7]:
#Predict which kind of fruit weighs 140 with bumpy skin
prediction = clf.predict([[140,1]])
labelPrediction(prediction)

Prediction:  Apple


In [8]:
#Try the different data feature combination

In [9]:
#Let's see if flipping the order of the features matters
features = np.column_stack((np.array(skin), np.array(weight)))
clf = clf.fit(features, fruit)
pred = clf.predict([[1,140]])
labelPrediction(pred)

Prediction:  Orange


In [10]:
#Looks like the order in which we place the features does not matter

In [11]:
#Making a set where the skin alternates, to test skin importance
#0 = Smooth, 1 = Bumpy
skin2 = [1 , 0, 1, 0]
weight2 = [140, 130, 150, 170]
#0=Apple 1=Orange
fruit2 = [0,0,1,1]
features2 = np.column_stack((np.array(skin2), np.array(weight2)))

print(features2)

clf2 = DecisionTreeClassifier()
clf2 = clf2.fit(features2, fruit2)

prediction2 = clf2.predict([[140,1]])
labelPrediction(prediction2)

[[  1 140]
 [  0 130]
 [  1 150]
 [  0 170]]
Prediction:  Apple


In [12]:
#Making a set where the weight alternates, to test weight importance
#0 = Smooth, 1 = Bumpy
skin3 = [0 , 0, 1, 1]
weight3 = [170, 130, 150, 140]
#0=Apple 1=Orange
fruit3 = [0, 0, 1, 1]
features3 = np.column_stack((np.array(skin3), np.array(weight3)))

print(features3)

clf3 = DecisionTreeClassifier()
clf3 = clf3.fit(features2, fruit)

prediction3 = clf3.predict([[140,1]])
labelPrediction(prediction3)

[[  0 170]
 [  0 130]
 [  1 150]
 [  1 140]]
Prediction:  Apple


In [13]:
#Both changes, skewed the data
#Leading me to believe that on a dataset this small both features are equally important

In [14]:
#App Recommendations
#The genders from our dataset
gender = ['F', 'F', 'M', 'F', 'M', 'M']
#Turn the gender into ints so we can use them
gender = [0, 0, 1, 0, 1, 1]

print(gender)

#The ages from our dataset
age = [15, 25, 32, 40, 12, 14]

#The apps tied to the data
app = ['Pokemon Go', 'WhatsApp', 'Snap Chat', 'WhatsApp', 'Pokemon Go', 'Pokemon Go']
#Making the app related to int 
#Pokemon Go = 0 WhatsApp = 1 Snap Chat = 2
app = [0, 1, 2, 1, 0, 0]

def listApp(pre):
    if pre == 0:
        print ('Pokemon Go')
    elif pre == 1:
        print ('WhatsApp')
    elif pre == 2:
        print ('Snap Chat')

appFeatures = np.column_stack((np.array(gender), np.array(age)))
print(appFeatures)

appClf = DecisionTreeClassifier()
appClf = appClf.fit(appFeatures, app)
#Predict app for Male, 21
appPred = appClf.predict([[1, 21]])
listApp(appPred)

[0, 0, 1, 0, 1, 1]
[[ 0 15]
 [ 0 25]
 [ 1 32]
 [ 0 40]
 [ 1 12]
 [ 1 14]]
Snap Chat


In [15]:
#Predict app for Female 18
appPred2 = appClf.predict([[0, 18]])
listApp(appPred2)

Pokemon Go
